import pygame

screen = pygame.display.set_mode((1280, 960))

def apple():
    appleA = pygame.image.load('images/apple_A.png')
    screen.blit(appleA, (0, 240))
    appleB = pygame.image.load('images/apple_B.png')
    screen.blit(appleB, (0, 350))
    appleC = pygame.image.load('images/apple_C.png')
    screen.blit(appleC, (120, 240))
    appleD = pygame.image.load('images/apple_D.png')
    screen.blit(appleD, (120, 350))
    appleE = pygame.image.load('images/apple_E.png')
    screen.blit(appleE, (240, 240))
    appleF = pygame.image.load('images/apple_F.png')
    screen.blit(appleF, (240, 350))
    appleG = pygame.image.load('images/apple_G.png')
    screen.blit(appleG, (360, 240))
    appleH = pygame.image.load('images/apple_H.png')
    screen.blit(appleH, (360, 350))
    appleI = pygame.image.load('images/apple_I.png')
    screen.blit(appleI, (1150, 240))
    appleJ = pygame.image.load('images/apple_J.png')
    screen.blit(appleJ, (810, 180))
    appleK = pygame.image.load('images/apple_K.png')
    screen.blit(appleK, (480, 440))
    appleL = pygame.image.load('images/apple_L.png')
    screen.blit(appleL, (480, 520))
    appleM = pygame.image.load('images/apple_M.png')
    screen.blit(appleM, (480, 0))
    appleN = pygame.image.load('images/apple_N.png')
    screen.blit(appleN, (700, 0))
    appleO = pygame.image.load('images/apple_O.png')
    screen.blit(appleO, (700, 80))
    appleP = pygame.image.load('images/apple_P.png')
    screen.blit(appleP, (480, 80))
    appleQ = pygame.image.load('images/apple_Q.png')
    screen.blit(appleQ, (480, 600))
    appleR = pygame.image.load('images/apple_R.png')
    screen.blit(appleR, (480, 680))
    appleS = pygame.image.load('images/apple_S.png')
    screen.blit(appleS, (700, 680))
    appleT = pygame.image.load('images/apple_T.png')
    screen.blit(appleT, (700, 600))
    appleU = pygame.image.load('images/apple_U.png')
    screen.blit(appleU, (700, 480))
    appleV = pygame.image.load('images/apple_V.png')
    screen.blit(appleV, (820, 550))
    appleW = pygame.image.load('images/apple_W.png')
    screen.blit(appleW, (1170, 170))
    appleX = pygame.image.load('images/apple_X.png')
    screen.blit(appleX, (1024, 600))
    appleY = pygame.image.load('images/apple_Y.png')
    screen.blit(appleY, (970, 440))
    appleZ = pygame.image.load('images/apple_Z.png')
    screen.blit(appleZ, (1070, 60))

def tree():
    tree = pygame.image.load("images/Tree.jpeg")
    screen.blit(tree, (460, 100))
